### ISSUE TITLE
I am curious about the effect of lora on ViT. Is there any literature or report on it？

### ISSUE THREAD

**Issue by leexinhao** [JamesQFreeman/LoRA-ViT#4]

**Comment by zhaozh10** [comment]
There are few papers in this area currently, but in our current experiments, ViT-LoRA has achieved better results than fully finetuned ViT (80+M) with extremely few learnable parameters (<1M) on different medical datasets concerning various modalities and organs. Some parts of our experiments are still underway, but we still believe that LoRA, as an efficient adaptation module, will have a wider impact in the coming Foundation Model era, not just in image generation.

**Comment by leexinhao** [comment]
> 
Thanks for your repy, it seems that most of the current papers about vison foundation model with PETL revolve around prompt and adapter. But obviously LoRA is much more efficient, so I am also trying to explore the application of lora in other vision tasks such as action recognition and image quality access.

**Comment by ttjjmm** [comment]
Thanks for your Information!

**Comment by TemugeB** [comment]
Hi. Thanks for sharing your code. I just wanted to ask a question about LoRA and ViT.

I'm trying to implement LoRA on ViT defined in [segment anything](https://github.com/facebookresearch/segment-anything/blob/main/segment_anything/modeling/image_encoder.py). But I'm not seeing any significant benefit in GPU memory usage while using LoRA over vanilla training. For example, ViT-b vanilla finetune uses 6.6GB GPU memory while LoRA uses 5.8GB GPU memory. This is with single image forward and backward pass. ViT-h won't fit on my 11GB GPU with LoRA. How much GPU memory usage reduction did you see in your testing?
