### ISSUE TITLE
How can I set up alpha?

### ISSUE THREAD

**Issue by baheytharwat** [JamesQFreeman/LoRA-ViT#7]
Thank you for your work and making it available!
I am not into the technical details of LoRA, but I know it accepts the rank and alpha as inputs. I see from the example you are providing that you specify r as input. but I don't see alpha is passed anywhere. so my question is what its current value? is it the same as rank? and how can I customize it for different values?

**Comment by AbsterZhu** [comment]
The code has been updated, and now you can set the alpha value when calling the LoRA function.

**Comment by baheytharwat** [comment]
Thank you @AbsterZhu for your immediate response! I will try it out and let you know if I have any issues.
